include ./theme.conf

shell fish

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size 12.0

url_style dotted
open_url_with default
underline_hyperlinks always
show_hyperlink_targets yes

sync_to_monitor yes

